# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f04e7a3bd20444e3366efaed26071ce0"
application_url = "https://blockbuilder.task19.com"
embedded = true
name = "Block Builder"

[auth]
redirect_urls = [ "https://blockbuilder.task19.com/auth/callback" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]
